---
- 21 Ruby Tricks You Should Be Using In Your Own Code.pdf
- Asynchronous DB- DBSlayer plus HTTP - igvita.com.pdf
- fat code is slow code - Polishing Ruby.pdf
- Introducing Cache Money - Magic Scaling Sprinkles.pdf
- Jay Fields' Thoughts- Is Distributed Development Viable.pdf
- Jay Fields' Thoughts- Ruby- inject.pdf
- Jay Fields' Thoughts- Ruby- Underuse of Modules.pdf
- Jay Fields' Thoughts_ Ruby_ Dynamically Define Method.pdf
- Meme Agora- Communication Channels - Cell Phones.pdf
- Ola Bini- Programming Language Synchronicity- Fractal Programming.pdf
- Rail Spikes- Testing is overrated.pdf
- RESTful contact forms — GIANT ROBOTS SMASHING INTO OTHER GIANT ROBOTS.pdf
- Ryan's Scraps- What's New in Edge Rails- Has Finder Functionality.pdf
- STEPHEN CHU . com- Seeing Rails Resources Clearly.pdf
- the { buckblogs -here }- Skinny Controller, Fat Model.pdf
- whytheluckystiff -- Seeing Metaclasses Clearly.pdf
